// Each row has a distinct conflict, saju explanation, and practical next step.
const rows = [
 ['divorce-word','이혼·관계 정리','싸울 때마다 이혼하자는 말이 나온다면','말이 끝나도 불안은 관계에 남으니까','사주 원국','말다툼 끝에 또 들었다|“그럼 그만 살자”','다음 날은 평소처럼 밥을 먹었다.|나만 아직 어제에 남아 있었다.','문제가 사라진 게 아니라|내가 말을 멈춘 건 아닐까','헤어질 운인지 궁금했지만|먼저 보고 싶은 건 반복되는 말이었다.','원국은 태어난 때의 간지로 구성한 명식이야.|누군가의 폭언을 정당화하는 이유는 아니야.','관계의 안전과 서로의 행동을 먼저 살펴.|위협을 견디는 게 좋은 궁합은 아니니까.','“관계를 끝내겠다는 말로 대화하지 말자.”|안전하게 말하기 어렵다면 도움부터 구하자.','말 한마디가 오래 남았던 적 있나요?','말의무게','tense kitchen; quiet breakfast; lingering sadness; tangled thread on table; setting a boundary; speaking to a trusted friend'],
 ['divorce-lonely','이혼·관계 정리','같이 사는데 더 외롭다는 마음','부부라는 이름만으로 채워지지 않는 것','일지','같은 소파에 앉아도|각자의 화면만 보고 있었다','오늘 있었던 일을 말하다가|어느 순간 혼잣말이 됐다.','함께 산다는 것과|함께 느낀다는 건 달랐다','사소한 대화를 포기할수록|우리 사이의 공백은 커졌다.','일지는 태어난 날의 지지야.|전통 명리에서 배우자궁으로 살피기도 해.','일지만으로 결혼 생활을 단정하진 않아.|실제로 마음을 주고받는지도 보아야 해.','오늘은 휴대폰을 내려놓고 10분.|해결책 없이 서로의 하루만 들어보자.','함께 있어도 외로웠던 순간이 있나요?','틈','two adults on sofa; ignored conversation; empty space between chairs; two thread spools; phones put aside; listening over tea'],
 ['divorce-stay','이혼·관계 정리','헤어질 이유보다 못 떠날 이유만 세고 있다면','두려움과 함께 살고 있는 건 아닌지','대운','처음에는 좋아서 남았고|이제는 무서워서 남는다','지나온 시간도 아깝고|혼자가 된 내 모습도 두려웠다.','남기로 한 선택과|떠날 수 없다는 생각','두 문장이 같은 뜻인 줄 알고|내 마음을 자꾸 미뤘다.','대운은 긴 주기의 운을 살피는 개념이야.|이혼할 날짜를 확정하는 명령은 아니야.','운의 해석보다 현재의 안전과 현실이 먼저야.|선택을 혼자 감당할 필요는 없어.','남고 싶은 이유와 두려운 이유를 나눠 적자.|필요하다면 신뢰하는 사람과 함께 살펴보자.','머무르는 이유가 달라진 적 있나요?','선택','standing at doorway; old shared belongings; two paths; seasonal tree; writing two blank notes; walking with trusted friend'],
 ['divorce-guilt','이혼·관계 정리','관계를 끝내고 싶은 내가 나쁜 사람일까?','미안함이 내 마음을 대신 결정하지 않도록','궁합','상대를 미워하지 않는데|함께 사는 건 힘들었다','좋았던 순간이 떠오르면|내가 너무 이기적인 것 같았다.','고마웠던 기억과|지금 힘든 마음은 함께 있어','한쪽을 지워야만|다른 쪽을 인정할 수 있는 건 아니었다.','궁합은 두 명식의 관계를 살피는 해석이야.|관계를 유지하라는 의무를 부여하진 않아.','좋았던 궁합이라는 말도 현재를 대신 못 해.|존중과 안전, 현실을 함께 살펴야 해.','상대를 평가하기 전에 나의 상태를 적어보자.|힘들다는 마음까지 부정하지는 말자.','고마움과 힘듦이 함께 남아 있다면?','마음의자리','holding old gift; tired at dining table; mixed emotions; two loose knots; reflecting in notebook; quiet window light'],
 ['destiny-coincidence','운명·인연','자꾸 우연히 마주치면 인연인 걸까?','우연이 설렘이 되는 순간, 놓치지 말아야 할 것','합','또 같은 시간에|같은 카페에서 만났다','이 정도면 인연인가 싶어서|작은 우연에 큰 의미를 붙였다.','마주친 횟수보다|서로 다가온 마음','운명처럼 보였던 건|내 기대가 만든 이야기일 수도 있었다.','합은 간지 사이의 결합 관계를 읽는 말이야.|우연히 마주쳤다는 사실과 같지는 않아.','명식의 합 하나가 관계를 보장하진 않아.|상대의 관심과 의사를 함께 확인해야 해.','운명인지 시험하기보다 가벼운 인사부터.|다가오는 마음이 서로의 것인지 살펴보자.','우연이 특별하게 느껴졌던 적 있나요?','우연','meeting at cafe; surprised glance; imagining red thread; two threads meeting; gentle greeting; reciprocal friendly conversation'],
 ['destiny-familiar','운명·인연','처음 만났는데 오래 안 사람 같았다','익숙한 느낌과 믿을 수 있는 사람의 차이','일주','말하지 않아도 통하는|느낌이 들었다','처음 만난 사람인데|벌써 내 편 같았다.','빨리 가까워지는 마음에|시간도 필요했다','익숙함이 좋았지만|아직 모르는 모습도 많았다.','일주는 태어난 날의 천간·지지 조합이야.|같은 일주여도 같은 삶을 살지는 않아.','일주의 공통점만으로 신뢰를 정하진 말자.|말과 행동이 맞는지 천천히 지켜봐도 돼.','설렘을 줄일 필요는 없어.|약속이 지켜지는 시간을 함께 쌓아보자.','첫 만남부터 익숙했던 사람이 있나요?','익숙함','first meeting; easy laughter; watching a clock; matching thread colors; keeping a small promise; walking calmly together'],
 ['destiny-late','운명·인연','내 인연만 늦게 오는 것 같을 때','친구들의 소식에 조급해진 날을 위해','세운','축하한다는 말을 하고|집에 와서는 울었다','다들 다음 장으로 넘어가는데|나만 같은 페이지 같았다.','늦었다는 기준은|누가 정한 걸까','내가 원하는 관계보다|남들의 시간표를 먼저 보고 있었다.','세운은 한 해의 흐름을 읽는 개념이야.|모두에게 같은 시기에 인연이 온단 뜻은 아니야.','운의 해석으로 나를 낙오자라 부르지 말자.|관계의 속도는 사람마다 다르니까.','남의 일정 대신 내가 원하는 관계를 적어보자.|시작할 준비도 나의 속도로 해도 돼.','남의 좋은 소식에 조급해진 적 있나요?','나의속도','celebrating friend; quiet trip home; open book with blank pages; seasons passing; choosing own path; hopeful morning walk'],
 ['destiny-loop','운명·인연','왜 늘 비슷한 사람에게 끌릴까?','이번엔 다를 거라 믿었는데 같은 장면이라면','십성','성격도 직업도 다른데|서운한 순간은 같았다','처음에는 나를 챙겨주더니|나중에는 내 선택까지 정하려 했다.','익숙한 끌림을|좋은 인연이라 믿었다','사랑받는 느낌과|내가 작아지는 느낌을 헷갈렸다.','십성은 일간과 다른 간의 관계를 읽는 틀이야.|연애 행동을 확정하는 진단표는 아니야.','이름보다 실제로 반복되는 상황을 보자.|존중이 줄어드는 관계를 운명으로 포장하지 말자.','좋았던 첫 장면과 힘들었던 장면을 나란히.|다음엔 초기에 확인할 경계 하나를 정해보자.','매번 비슷한 이유로 서운해진다면?','반복','meeting new adult; controlling gesture at a cafe; similar doorways; repeating thread loops; comparing blank notes; choosing a boundary'],
 ['marriage-money','부부·결혼','돈 이야기를 하면 왜 사랑까지 의심할까?','씀씀이보다 먼저 다른 건 안심하는 방법','오행','나는 모아야 안심이고|그는 써야 행복하다고 했다','같은 돈을 보면서|우리는 다른 미래를 생각했다.','서로를 평가하다가|정작 걱정은 말하지 못했다','아끼자는 말 뒤에는 불안이|즐기자는 말 뒤에는 지친 마음이 있었다.','오행은 다섯 요소의 관계를 읽는 전통의 틀이야.|소비 습관을 하나의 오행으로 결정하진 않아.','궁합을 살필 때도 현실의 생활 방식을 빼놓지 마.|숫자 뒤의 마음부터 서로 들어보자.','잘잘못 대신 “나는 이럴 때 불안해”부터.|두 사람이 편한 기준을 함께 찾아보자.','씀씀이가 달라 서운했던 적 있나요?','생활궁합','household conversation; savings jar; two imagined futures; five thread colors; honest listening; arranging household items together'],
 ['marriage-family','부부·결혼','우리 둘의 관계에 가족이 자꾸 들어올 때','좋은 사람이고 싶어서 못 했던 말','일지','부모님 말도 맞는 것 같고|내 마음도 서운했다','갈등을 피하려고 웃었는데|집에 와서는 배우자에게 화가 났다.','가족을 존중하는 것과|우리 경계를 지우는 것','둘 중 하나만|선택해야 하는 줄 알았다.','일지는 태어난 날의 지지로|배우자궁을 살필 때 거론하기도 해.','일지 하나로 가족 갈등을 예고하진 않아.|실제 역할과 경계를 함께 의논해야 해.','상대 가족을 평가하기보다 우리 기준부터.|둘이 함께 말할 한 문장을 정해보자.','가족 앞에서 못 했던 말이 있나요?','우리의선','family gathering; forced smile; quiet walk home; thread boundary around two chairs; couple discussion; standing together calmly'],
 ['marriage-apology','부부·결혼','미안하다는 말은 들었는데 왜 안 풀릴까?','사과와 관계 회복 사이에 남은 장면','합·충','미안하다는 말 뒤에|그런데가 붙었다','사과를 받은 것 같은데|또 내가 설명하고 있었다.','듣고 싶은 건 승패보다|내 마음을 알았다는 말','정답을 가리다가|서운함의 자리를 놓쳤다.','합과 충은 간지의 관계를 읽는 용어야.|사과할 능력을 정해주는 표시는 아니야.','잘 맞는 명식이라는 말보다|다툰 뒤 실제로 달라지는 행동도 중요해.','“내가 왜 속상했는지 한 번만 들어줘.”|설명이 끝난 다음 서로의 부탁을 말해보자.','어떤 사과가 마음에 닿았나요?','회복','apology conversation; interrupted explanation; listening closely; crossed threads; giving time to speak; repaired loose knot'],
 ['marriage-doubt','부부·결혼','결혼을 앞두고 확신이 줄었다면','설렘과 생활 사이에서 생긴 질문들','궁합','좋아하는 건 확실한데|함께 살 자신은 흔들렸다','축하받을 일인데|혼자 고민하는 내가 이상한 줄 알았다.','사랑이 부족해서가 아니라|질문이 구체적이 된 것','집안일도 갈등도 가족도|둘의 일이 된다는 걸 느꼈다.','궁합은 두 명식의 상호 관계를 살피는 해석이야.|결혼의 성공을 보증하는 점수는 아니야.','좋고 나쁨 한마디보다 현실적인 대화가 필요해.|합의하지 못한 부분을 남겨두지 말자.','함께 살 하루를 구체적으로 이야기해보자.|누가 무엇을 맡고 어떻게 쉬고 싶은지.','결혼 전에 꼭 나누고 싶은 대화는?', '같이살기','looking at rings; thoughtful at window; shared home doorway; two thread spools; discussing daily routines; preparing a meal together'],
 ['reunion-social','재회','스토리는 보는데 연락은 없는 사람','조회 기록을 마음의 답으로 읽고 있다면','재회운','내 게시물은 빠짐없이|보는 것 같았다','아직 마음이 있나 싶어서|더 자주 휴대폰을 열었다.','기록은 있었지만|대화는 시작되지 않았다','보았다는 사실에|원하는 뜻을 붙이고 있었다.','재회운은 다시 만날 흐름을 논하는 해석이야.|조회 기록만으로 명식이나 속마음을 알 순 없어.','관심처럼 보이는 신호와 관계를 원한다는 의사는|같지 않을 수 있어. 단정을 잠시 멈춰보자.','조회 목록을 확인하는 시간을 줄여보자.|추측 대신 실제 대화가 있었는지 돌아보자.','작은 신호를 오래 해석한 적 있나요?','신호','checking blank social screen; waiting for message; empty chat scene; red thread near phone; putting phone away; spending time outdoors'],
 ['reunion-change','재회','다시 만났는데 같은 이유로 또 싸운다면','재회보다 어려운 건 새로운 관계를 만드는 일','세운','돌아오기만 하면|괜찮을 줄 알았다','처음 며칠은 좋았는데|익숙한 서운함이 다시 찾아왔다.','다시 시작한 날짜만|바뀐 건 아니었을까','우리는 재회는 했지만|헤어진 이유를 다루진 않았다.','세운은 한 해의 운 흐름을 살피는 말이야.|새 시기가 지난 갈등을 저절로 풀진 않아.','재회 흐름을 보더라도 현실의 변화가 함께 필요해.|누가 무엇을 달리할지 구체적으로 말해보자.','이전과 달라질 행동을 각자 하나씩.|말뿐 아니라 지켜지는지 시간을 두고 보자.','다시 시작할 때 무엇이 달라져야 할까요?','새시작','meeting again; initial happy walk; familiar disagreement; seasonal shift; agreeing small actions; practicing listening'],
 ['compatibility-expression','궁합','사랑한다는 말보다 행동이 먼저인 사람','표현의 방식이 다를 때 생기는 오해','일간','집에 잘 도착했는지는 묻는데|보고 싶다는 말은 없었다','챙겨주는 건 느껴지는데|확신은 자꾸 부족했다.','내가 알아들을 수 있는|표현도 필요했다','행동으로 보여준다는 말과|말로 듣고 싶다는 마음이 만났다.','일간은 태어난 날의 천간을 뜻해.|표현 방식을 이것 하나로 확정하진 않아.','명식의 성향을 참고하더라도 직접 부탁해도 돼.|상대가 원하는 표현도 함께 들어보자.','“챙겨줘서 고마워. 가끔 말로도 듣고 싶어.”|인정과 부탁을 같은 문장에 담아보자.','어떤 표현에서 사랑을 느끼나요?','표현','helping with coat; quiet ride home; uncertain expression; soft thread gift; asking warmly; sincere conversation'],
 ['compatibility-reassure','궁합','확신을 달라고 할수록 멀어지는 관계','확인하고 싶은 마음이 끝나지 않는다면','명식','좋아하냐고 물으면|좋아한다고 답했다','잠깐 안심했지만|다음 날 또 같은 질문을 했다.','필요했던 건 대답 하나보다|예측할 수 있는 행동','말을 더 듣는 것만으로는|마음의 빈칸이 채워지지 않았다.','명식은 태어난 때의 간지를 정리한 구조야.|상대의 진심을 실시간으로 읽는 도구는 아니야.','성향을 살피는 일과 신뢰를 쌓는 일은 달라.|일관된 말과 행동이 있는지도 돌아보자.','“약속이 바뀔 땐 미리 알려주면 안심돼.”|막연한 확인을 구체적인 부탁으로 바꿔보자.','어떤 행동이 마음을 안심시키나요?','안심','asking for reassurance; brief relief; repeated uncertainty; incomplete thread circle; making a clear request; calm consistent meeting'],
];
module.exports = rows.map(([id,category,title,hook,sajuKeyword,story,situation,turn,feeling,term,nuance,action,question,keyword,scenes])=>({id,category,title,hook,sajuKeyword,story:story.split('|'),situation:situation.split('|'),turn:turn.split('|'),feeling:feeling.split('|'),term:term.split('|'),nuance:nuance.split('|'),action:action.split('|'),question,keyword,scenes}));
